### Kitty Config file ###

copy_on_select on 
background_opacity 0.9
background_blur 8

#background_image /home/rasmus/Pictures/wallpaper/117066701_p0_master1200.jpg
#background_image_layout cscaled

### UI ###
# Fonts
# font_family       JetBrainsMono Nerd
# bold_font         auto
# italic_font       auto
# bold_italic_font  auto
font_size         12.0


# The basic colors
foreground              #282828
background              #ebdbb2
selection_foreground    #ebdbb2
selection_background    #665c59

# Cursor colors
cursor                  #282828
cursor_text_color       #ebdbb2

# URL underline color when hovering with mouse
url_color               #458588

# Kitty window border colors
active_border_color     #d79921
inactive_border_color   #665c59

bell_border_color       #b17286

# OS Window titlebar colors
wayland_titlebar_color system


### Color ###
# Tab bar colors
active_tab_foreground   #ebdbb2
active_tab_background   #282828
inactive_tab_foreground #282828
inactive_tab_background #665c59
tab_bar_background      #181926

# Colors for marks (marked text in the terminal)
mark1_foreground #24273a
mark1_background #b7bdf8
mark2_foreground #24273a
mark2_background #c6a0f6
mark3_foreground #24273a
mark3_background #7dc4e4

## 16 terminal colors ##
# black
color0 #282828
color8 #665c59

# red
color1 #af3a03
color9 #b17286

# green
color2  #899473
color10 #899473

# yellow
color3  #d79921
color11 #d79921

# blue
color4  #458588
color12 #83a598

# magenta
color5  #b17286
color13 #b17286

# cyan
color6  #83a598
color14 #83a598

# white
color7  #e0c88a
color15 #fbf1c7



### Layouts ###
enabled_layouts tall:bisa=50;fullsize=1;mirrored=false


### key bind mapping ###
# Horisontal splitting
map f5 launch --location=hsplit

# Vertical splitting
map f6 launch --location=vsplit


# Move active window
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

# Switch focus to the neighboring window in the indicated direction
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
