#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = waybar & hyprpaper & hyprlock
exec-once = dunst


# for keyboard macros/remapping
exec-once = sudo keyd

windowrule = workspace 2 silent, match:class ^discord$
windowrule = workspace 2 silent, match:class ^steam$
windowrule = workspace 2 silent, match:class ^spotify-launcher$

# open discord, spotify, steam
exec-once = kitty
exec-once = discord
exec-once = steam
#exec-once = spotify-launcher

# for polkit authentication agent
exec-once = systemctl --user start hyprpolkitagent
exec-once = /usr/bin/gnome-keyring-deamon --start --components=secrets

# Runs a git pull on startup for my obsidan notes
exec-once = bash ~/Script/GitPullObsidian.sh
