
#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = STEAM_ENABLE_WAYLAND,1

# start open with file in dolphin
env = XDG_MENU_PREFIX,arch-

# File association in dolphin
#env = XDG_MENU_PREFIX,plasma-

###################
### PERMISSIONS ###
###################

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/windowRuleWorkspaces.conf
source = ~/.config/hypr/inputs.conf
source = ~/.config/hypr/bind.conf
source = ~/.config/hypr/lookAndFeel.conf
source = ~/.config/hypr/autoStart.conf
