##  NOTES
##  fit_mode = contain|cover|tile|fill
##

# monitor 1
wallpaper {
  monitor = DP-1
  path = ~/Pictures/wallpaper/ghibil.jpg
  fit_mode= cover
}
# monitor 2
wallpaper {
  monitor = DP-2
  path = ~/Pictures/wallpaper/ghibli.jpg
  fit_mode= cover
}
# fallback wallpaper
wallpaper {
  monitor = 
  path = ~/Pictures/wallpaper/ghibli.jpg
  fit_mode= cover
}


